-- 코드를 작성해주세요
SELECT C.ID, COALESCE(D.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA C LEFT JOIN (SELECT A.ID, COUNT(A.ID) AS CHILD_COUNT
FROM ECOLI_DATA A JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
GROUP BY A.ID) D
ON C.ID = D.ID
ORDER BY ID
