-- 코드를 입력하세요
WITH T AS (SELECT USER_ID, PRODUCT_ID
            FROM ONLINE_SALE
            GROUP BY USER_ID, PRODUCT_ID, SALES_DATE)

SELECT USER_ID, PRODUCT_ID
FROM T
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID) >= 2
ORDER BY USER_ID, PRODUCT_ID DESC;