-- 회원 ID, 성별, 나이, 가입일
-- 상품 판매 ID, 회원 ID, 상품 ID, 판매량, 판매일

WITH T AS (SELECT USER_ID
          FROM USER_INFO
          WHERE YEAR(JOINED) = 2021)

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
        COUNT(DISTINCT T.USER_ID) PURCHASED_USERS,
        ROUND(COUNT(DISTINCT T.USER_ID) / (SELECT COUNT(*) FROM T),1) PURCHASED_RATIO
FROM ONLINE_SALE A JOIN T ON A.USER_ID = T.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH