-- 코드를 입력하세요
WITH H AS (SELECT car.CAR_TYPE, DAILY_FEE, HISTORY_ID, 
            DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
            CASE WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN '90일 이상'
                 WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN '30일 이상'
                 WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN '7일 이상'
                 ELSE 'NONE' END AS DURATION_TYPE
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY his JOIN CAR_RENTAL_COMPANY_CAR car
            ON his.CAR_ID = car.CAR_ID
            WHERE car.CAR_TYPE = '트럭')


SELECT H.HISTORY_ID, ROUND(H.PERIOD * H.DAILY_FEE * (100-IFNULL(P.DISCOUNT_RATE,0))/100) AS FEE
FROM H LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON H.DURATION_TYPE = P.DURATION_TYPE AND H.CAR_TYPE = P.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC




