-- 코드를 입력하세요
SELECT AP.APNT_NO, P.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP JOIN DOCTOR D ON AP.MDDR_ID = D.DR_ID
JOIN PATIENT P ON AP.PT_NO = P.PT_NO
WHERE DATE_FORMAT(AP.APNT_YMD,'%Y-%m-%d') = '2022-04-13' AND AP.APNT_CNCL_YN = 'N' AND AP.MCDP_CD = 'CS'
ORDER BY APNT_YMD