-- 코드를 작성해주세요
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO C JOIN
(SELECT B.ITEM_ID
FROM ITEM_INFO A JOIN ITEM_TREE B
ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE A.RARITY = 'RARE') D
ON C.ITEM_ID = D.ITEM_ID
ORDER BY C.ITEM_ID DESC
