SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.MAX - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A JOIN 
(SELECT MAX(SIZE_OF_COLONY) AS MAX,YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR, YEAR_DEV
