-- 코드를 작성해주세요
SELECT B.YEAR, (B.SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A 
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) SIZE
      FROM ECOLI_DATA
      GROUP BY YEAR
     ) B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR, YEAR_DEV