WITH T AS (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX
          FROM ECOLI_DATA
          GROUP BY YEAR)

SELECT T.YEAR, (T.MAX - A.SIZE_OF_COLONY) YEAR_DEV, A.ID
FROM ECOLI_DATA A JOIN T ON YEAR(A.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY T.YEAR, YEAR_DEV