-- 코드를 작성해주세요
WITH T AS (SELECT FISH_TYPE, MAX(LENGTH) LENGTH
            FROM FISH_INFO
            GROUP BY FISH_TYPE)
            
SELECT ID, FISH_NAME, T.LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE JOIN T ON A.FISH_TYPE = T.FISH_TYPE
WHERE A.FISH_TYPE = T.FISH_TYPE AND A.LENGTH = T.LENGTH
ORDER BY ID;