-- 부서 ID, 국문 부서명, 영문 부서명, 부서 위치
-- 사번, 성명, 부서 ID, 직책, 이메일, 전화번호, 입사일, 연봉
-- 사번, 연도, 반기, 평가 점수

SELECT SUM(SCORE) AS SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
GROUP BY EMP_NO, EMP_NAME, POSITION, EMAIL
ORDER BY SCORE DESC
LIMIT 1
