-- 코드를 작성해주세요
SELECT A.DEPT_ID, A.DEPT_NAME_EN, ROUND(B.SUM_SAL/CNT,0) AS AVG_SAL
FROM HR_DEPARTMENT A JOIN 
(SELECT DEPT_ID, SUM(SAL) AS SUM_SAL, COUNT(DEPT_ID) AS CNT
FROM HR_EMPLOYEES
GROUP BY DEPT_ID) B
ON A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_ID
ORDER BY AVG_SAL DESC
