-- 부서 ID, 국문 부서명, 영문 부서명, 부서 위치
-- 사번, 성명, 부서 ID, 직책, 이메일, 전화번호, 입사일, 연봉
SELECT A.DEPT_ID, A.DEPT_NAME_EN, ROUND(AVG(B.SAL),0) AVG_SAL
FROM HR_DEPARTMENT A JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_ID, A.DEPT_NAME_EN
ORDER BY AVG_SAL DESC
