-- 식품 ID, 식품 이름, 식품코드, 식품분류, 식품 가격

WITH T AS (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
          FROM FOOD_PRODUCT
          WHERE CATEGORY IN ('과자','국','김치','식용유')
          GROUP BY CATEGORY)
          
SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A JOIN T ON A.CATEGORY = T.CATEGORY
WHERE A.PRICE = T.MAX_PRICE
ORDER BY A.PRICE DESC